# Generated by Django 3.2.4 on 2021-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subscription',
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
